import type { ComponentType } from "react";
import {
  IconBook,
  IconBulb,
  IconCalendarCheck,
  IconChalkboard,
  IconCheckbox,
  IconChecklist,
  IconClipboardCheck,
  IconClipboardText,
  IconClock,
  IconDeviceDesktop,
  IconEar,
  IconEye,
  IconFlag,
  IconFlame,
  IconHandClick,
  IconHandStop,
  IconHeart,
  IconLighter,
  IconMathSymbols,
  IconMessage,
  IconMessageCircle,
  IconMicroscope,
  IconMoodSmile,
  IconNote,
  IconNotebook,
  IconPencil,
  IconPresentation,
  IconPuzzle,
  IconRocket,
  IconSchool,
  IconSearch,
  IconSpeakerphone,
  IconStar,
  IconStretching,
  IconTarget,
  IconThumbUp,
  IconTrophy,
  IconUser,
  IconUserHeart,
  IconUsers,
  IconVolume,
  IconWand,
  IconWriting,
} from "@tabler/icons-react";

type IconComponent = ComponentType<{ size?: number; stroke?: number }>;

/**
 * Maps skill IDs from the taxonomy to Tabler icon components.
 * Falls back to DEFAULT_SKILL_ICON for unmapped skills.
 */
export const SKILL_ICON_MAP: Record<string, IconComponent> = {
  // Intellectual Preparation
  "complete-mastery-checks": IconCheckbox,
  "complete-assessments": IconClipboardCheck,
  "complete-unit-unpack-protocol": IconNotebook,
  "prepare-fluency-materials": IconMathSymbols,
  "complete-number-strings-internalization": IconPencil,
  "prepare-sgi-materials": IconClipboardText,
  "select-students-for-small-group": IconUsers,
  "complete-worked-example-and-practice-problems": IconChecklist,
  "prepare-for-cfu": IconSearch,
  "prepare-to-respond-to-student-errors": IconWand,
  "prepare-inquiry-materials": IconMicroscope,
  "select-students-for-inquiry-groups": IconUsers,
  "complete-inquiry-tasks": IconPuzzle,
  "review-answer-key-for-misconceptions": IconEye,
  "review-student-work-on-podsie": IconDeviceDesktop,

  // Lesson Launch
  "greeting-every-student-by-name": IconMoodSmile,
  "minute-drills": IconClock,
  "lead-whole-class-warm-up-nyse": IconChalkboard,
  "attendance-lesson-completion-data-share": IconPresentation,
  "one-on-one-data-conversations": IconMessage,
  "individual-class-celebrations": IconTrophy,
  "work-time-goal": IconTarget,
  "gathering-materials-routine": IconNote,

  // Small Group Instruction
  "set-up-physical-environment": IconSchool,
  "use-visual-anchors": IconEye,
  "explain-steps-sequential-order": IconChecklist,
  "articulate-stamp-big-idea": IconBulb,
  "use-precise-math-vocabulary": IconMathSymbols,
  "use-concise-language": IconMessageCircle,
  "accurately-explain-math-concepts": IconBook,
  "ask-cfu-questions-worked-example": IconSearch,
  "use-teacher-wait-time": IconClock,
  "facilitate-student-to-student-relationships": IconUsers,
  "normalize-mistakes-as-learning-sgi": IconHeart,
  "promote-growth-mindset-sgi": IconRocket,
  "lead-turn-and-talk": IconMessage,
  "facilitate-student-independent-practice": IconWriting,
  "notice-error-prompt-worked-example": IconEye,
  "respond-one-on-one-to-student-error": IconUserHeart,

  // Inquiry Groups
  "state-inquiry-norms-explicitly": IconSpeakerphone,
  "inquiry-only-during-double-blocks": IconCalendarCheck,
  "inquiry-during-all-periods": IconCalendarCheck,
  "check-in-after-five-minutes": IconClock,
  "monitor-for-visible-collaboration": IconEye,
  "facilitate-understanding-the-question-protocol": IconEar,
  "use-facilitative-questioning": IconMessageCircle,
  "push-thinking-with-teacher-marker": IconPencil,
  "elevate-student-language-math-terminology": IconVolume,
  "cold-call-group-members-to-explain": IconHandClick,
  "mobilize-knowledge-across-groups": IconUsers,

  // Lesson Closing
  "close-lesson-with-urgency": IconFlame,
  "lead-efficient-safe-cleanup": IconHandStop,
  "close-lesson-with-celebrations": IconTrophy,
  "student-self-evaluation": IconStretching,

  // Culture
  "address-students-by-name": IconUser,
  "celebrate-using-specific-praise": IconStar,
  "celebrate-whole-class": IconTrophy,
  "assure-and-affirm": IconThumbUp,
  "build-personal-rapport": IconUserHeart,
  "emotional-regulation": IconHeart,
  "learn-about-value-student-identities": IconUsers,
  "identity-awareness-self-reflection": IconMicroscope,
  "attention-grabber": IconSpeakerphone,
  "specific-observable-directions": IconTarget,
  "concise-sequential-directions": IconChecklist,
  rationale: IconBulb,
  "scan-positive-narration": IconEye,
  "observable-directions-l2": IconTarget,
  "multi-modal-directions": IconPresentation,
  "student-led-directions": IconUsers,
  "introduce-step-by-step-routines": IconClipboardText,
  "routine-procedure-practice": IconStretching,
  "build-urgency": IconFlame,
  "foster-student-ownership-of-culture": IconFlag,
  "keep-corrections-off-stage": IconLighter,
  "use-proximity": IconHandStop,
  "calm-voice-neutral-language": IconVolume,
  "positive-redirection": IconThumbUp,
  "support-reminder-non-verbal-cues": IconHandClick,
  "anonymous-group-reminders": IconMessage,
  "curious-one-on-one-interaction": IconMessageCircle,
  "communicate-high-expectations": IconRocket,
  "emphasize-collective-success": IconUsers,
  "encourage-academic-risk-taking": IconFlame,
  "model-enthusiasm-curiosity": IconStar,
  "student-goal-setting": IconTarget,
  "normalize-mistakes-as-learning": IconHeart,
  "promote-growth-mindset": IconRocket,
  "specific-actionable-feedback": IconWriting,
};

export const DEFAULT_SKILL_ICON: IconComponent = IconBulb;

export function getSkillIcon(skillId: string): IconComponent {
  return SKILL_ICON_MAP[skillId] ?? DEFAULT_SKILL_ICON;
}
