"use client";

import { Badge } from "@/components/core/feedback/Badge";
import type { DiagramEvolution } from "../../lib/types";

interface SlidePlanDisplayProps {
  diagramEvolution: DiagramEvolution;
  visualType?: string;
  svgSubtype?: string;
  stepCount?: number;
}

// Color schemes for step headers (cycles through these)
const STEP_COLORS = [
  { bg: "bg-amber-50", text: "text-amber-800", border: "border-amber-200" },
  {
    bg: "bg-emerald-50",
    text: "text-emerald-800",
    border: "border-emerald-200",
  },
  { bg: "bg-purple-50", text: "text-purple-800", border: "border-purple-200" },
  { bg: "bg-rose-50", text: "text-rose-800", border: "border-rose-200" },
  { bg: "bg-cyan-50", text: "text-cyan-800", border: "border-cyan-200" },
  { bg: "bg-orange-50", text: "text-orange-800", border: "border-orange-200" },
];

/**
 * Displays the diagram evolution preview showing how the visual develops
 * step-by-step across slides. This helps teachers visualize and approve
 * the progression before slide generation.
 *
 * The ASCII content is generated by the LLM during the analysis phase.
 * DiagramEvolution includes: initialState, keyElements, and step-by-step progression.
 */
export function SlidePlanDisplay({
  diagramEvolution,
  visualType,
  svgSubtype,
  stepCount,
}: SlidePlanDisplayProps) {
  return (
    <div className="space-y-4">
      {/* All slides in responsive grid: Problem Setup + Step slides */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Problem Setup Slide */}
        <div className="border border-gray-200 rounded-lg overflow-hidden">
          <div className="bg-blue-50 px-3 py-1.5 border-b border-blue-200">
            <h4 className="text-xs font-semibold text-blue-800">
              Problem Setup
            </h4>
          </div>
          <div className="p-3">
            <pre className="bg-gray-900 text-green-400 rounded-lg p-3 text-xs font-mono overflow-x-auto whitespace-pre">
              {diagramEvolution.initialState}
            </pre>
          </div>
        </div>

        {/* Step-by-step evolution */}
        {diagramEvolution.steps.map((step, index) => {
          const colors = STEP_COLORS[index % STEP_COLORS.length];
          return (
            <div
              key={index}
              className="border border-gray-200 rounded-lg overflow-hidden"
            >
              {/* Step header */}
              <div
                className={`${colors.bg} px-3 py-1.5 border-b ${colors.border}`}
              >
                <h4 className={`text-xs font-semibold ${colors.text}`}>
                  {step.header}
                </h4>
              </div>

              {/* ASCII diagram */}
              <div className="p-3">
                <pre className="bg-gray-900 text-green-400 rounded-lg p-3 text-xs font-mono overflow-x-auto whitespace-pre">
                  {step.ascii}
                </pre>
              </div>

              {/* Changes section */}
              {step.changes.length > 0 && (
                <div className="px-3 py-2 bg-gray-50 border-t border-gray-100">
                  <h5 className="text-xs font-medium text-gray-600 mb-1">
                    Changes:
                  </h5>
                  <ul className="space-y-0.5">
                    {step.changes.map((change, changeIndex) => (
                      <li
                        key={changeIndex}
                        className="flex items-start gap-1.5 text-xs"
                      >
                        <span className="text-green-600 font-medium">+</span>
                        <span className="text-gray-700">{change}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          );
        })}
      </div>

      {/* Key Elements legend */}
      {diagramEvolution.keyElements &&
        diagramEvolution.keyElements.length > 0 && (
          <div className="border border-gray-200 rounded-lg overflow-hidden">
            <div className="bg-gray-50 px-4 py-2 border-b border-gray-200">
              <h4 className="text-sm font-semibold text-gray-700">
                Key Elements
              </h4>
            </div>
            <div className="p-4">
              <ul className="space-y-2">
                {diagramEvolution.keyElements.map((el, i) => (
                  <li key={i} className="flex items-start gap-2 text-sm">
                    <span className="text-gray-600 font-medium">
                      {el.element}:
                    </span>
                    <span className="text-gray-500">{el.represents}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      {/* Visual type info badges at bottom */}
      {(visualType || svgSubtype || stepCount) && (
        <div className="flex items-center gap-3 flex-wrap pt-2">
          {visualType && (
            <Badge intent="info" size="xs">
              {visualType}
            </Badge>
          )}
          {svgSubtype && (
            <Badge intent="secondary" size="xs">
              {svgSubtype}
            </Badge>
          )}
          {stepCount && (
            <span className="text-xs text-gray-500">{stepCount} steps</span>
          )}
        </div>
      )}
    </div>
  );
}
