// Domain labels for display
export const DOMAIN_LABELS: Record<string, string> = {
  EE: "Expressions & Equations",
  G: "Geometry",
  RP: "Ratios & Proportions",
  NS: "Number System",
  SP: "Statistics & Probability",
  F: "Functions",
  Other: "Other",
};

// Domain colors for badges
export const DOMAIN_COLORS: Record<string, { bg: string; border: string; text: string; badge: string }> = {
  EE: { bg: "bg-blue-50", border: "border-blue-200", text: "text-blue-700", badge: "bg-blue-500" },
  G: { bg: "bg-green-50", border: "border-green-200", text: "text-green-700", badge: "bg-green-500" },
  RP: { bg: "bg-purple-50", border: "border-purple-200", text: "text-purple-700", badge: "bg-purple-500" },
  NS: { bg: "bg-orange-50", border: "border-orange-200", text: "text-orange-700", badge: "bg-orange-500" },
  SP: { bg: "bg-pink-50", border: "border-pink-200", text: "text-pink-700", badge: "bg-pink-500" },
  F: { bg: "bg-teal-50", border: "border-teal-200", text: "text-teal-700", badge: "bg-teal-500" },
  Other: { bg: "bg-gray-50", border: "border-gray-200", text: "text-gray-700", badge: "bg-gray-500" },
};

// Standard descriptions for tooltips
export const STANDARD_DESCRIPTIONS: Record<string, string> = {
  // Expressions & Equations - Grade 8
  "8.EE.1": "Know and apply the properties of integer exponents",
  "8.EE.2": "Use square root and cube root symbols",
  "8.EE.3": "Use numbers expressed in scientific notation",
  "8.EE.4": "Perform operations with numbers in scientific notation",
  "8.EE.5": "Graph proportional relationships; interpret unit rate as slope",
  "8.EE.6": "Use similar triangles to explain slope; derive y = mx + b",
  "8.EE.7": "Solve linear equations in one variable",
  "8.EE.8": "Analyze and solve systems of linear equations",
  // Geometry - Grade 8
  "8.G.1": "Verify properties of rotations, reflections, and translations",
  "8.G.2": "Describe congruence using transformations",
  "8.G.3": "Describe dilations and similarity transformations",
  "8.G.4": "Understand similarity of two-dimensional figures",
  "8.G.5": "Use angle relationships (parallel lines, triangles, exterior angles)",
  "8.G.6": "Explain the Pythagorean Theorem and its converse",
  "8.G.7": "Apply the Pythagorean Theorem in real-world problems",
  "8.G.8": "Apply the Pythagorean Theorem to find distance",
  "8.G.9": "Know formulas for cones, cylinders, and spheres",
  // Functions - Grade 8
  "8.F.1": "Understand functions as rules with unique outputs",
  "8.F.2": "Compare properties of functions represented differently",
  "8.F.3": "Interpret the equation y = mx + b as linear",
  "8.F.4": "Construct a function to model a linear relationship",
  "8.F.5": "Describe qualitative features of a function from a graph",
  // Number System - Grade 8
  "8.NS.1": "Know that irrational numbers exist",
  "8.NS.2": "Use rational approximations of irrational numbers",
  // Statistics & Probability - Grade 8
  "8.SP.1": "Construct and interpret scatter plots",
  "8.SP.2": "Understand straight lines and linear associations",
  "8.SP.3": "Use equations of linear models to solve problems",
  "8.SP.4": "Understand two-way frequency tables",
  // Grade 7 standards
  "7.RP.1": "Compute unit rates with ratios of fractions",
  "7.RP.2": "Recognize and represent proportional relationships",
  "7.RP.3": "Use proportional relationships to solve problems",
  "7.NS.1": "Apply and extend properties of operations to add/subtract rationals",
  "7.NS.2": "Apply and extend properties of operations to multiply/divide rationals",
  "7.NS.3": "Solve real-world problems with rational numbers",
  "7.EE.1": "Apply properties of operations to add, subtract, factor, expand",
  "7.EE.2": "Rewrite expressions in different forms",
  "7.EE.3": "Solve multi-step real-world problems with rationals",
  "7.EE.4": "Solve inequalities and equations",
  "7.G.1": "Solve problems involving scale drawings",
  "7.G.2": "Draw geometric shapes with given conditions",
  "7.G.3": "Describe 2D figures from slicing 3D figures",
  "7.G.4": "Know formulas for area and circumference of circles",
  "7.G.5": "Use facts about supplementary, complementary, vertical angles",
  "7.G.6": "Solve real-world problems involving area, volume, surface area",
  "7.SP.1": "Understand random sampling",
  "7.SP.2": "Use data from random samples to draw inferences",
  "7.SP.3": "Assess visual overlap of data distributions",
  "7.SP.4": "Use measures of center and variability to compare",
  "7.SP.5": "Understand probability as a number between 0 and 1",
  "7.SP.6": "Approximate probability by collecting data",
  "7.SP.7": "Develop probability models",
  "7.SP.8": "Find probabilities of compound events",
  // Grade 7 substandards (scraped from NY Standards documentation)
  "7.EE.4a": "Solve word problems leading to equations of the form px + q = r and p(x + q) = r",
  "7.EE.4b": "Solve word problems leading to inequalities of the form px + q > r or px + q < r",
  "7.NS.1a": "Describe situations in which opposite quantities combine to make 0",
  "7.NS.1b": "Understand p + q as the number located a distance |q| from p",
  "7.NS.1c": "Understand subtraction of rational numbers as adding the additive inverse",
  "7.NS.1d": "Apply properties of operations as strategies to add and subtract rational numbers",
  "7.NS.2a": "Understand that multiplication is extended from fractions to rational numbers",
  "7.NS.2b": "Understand that integers can be divided, provided that the divisor is not zero",
  "7.NS.2c": "Apply properties of operations as strategies to multiply and divide rational numbers",
  "7.NS.2d": "Convert a rational number to a decimal using long division",
  "7.RP.2a": "Decide whether two quantities are in a proportional relationship",
  "7.RP.2b": "Identify the constant of proportionality (unit rate) in tables, graphs, equations",
  "7.RP.2c": "Represent proportional relationships by equations",
  "7.RP.2d": "Explain what a point (x, y) on the graph of a proportional relationship means",
  "7.SP.7a": "Develop a uniform probability model by assigning equal probability to all outcomes",
  "7.SP.7b": "Develop a probability model by observing frequencies in data from a chance process",
  "7.SP.8a": "Understand that the probability of a compound event is the fraction of outcomes",
  "7.SP.8b": "Represent sample spaces for compound events using lists, tables and tree diagrams",
  "7.SP.8c": "Design and use a simulation to generate frequencies for compound events",
  // Grade 6 standards
  "6.RP.1": "Understand ratio concepts and ratio language",
  "6.RP.2": "Understand unit rate concepts",
  "6.RP.3": "Use ratio and rate reasoning to solve problems",
  "6.NS.1": "Interpret and compute quotients of fractions",
  "6.NS.2": "Fluently divide multi-digit numbers",
  "6.NS.3": "Fluently add, subtract, multiply, divide decimals",
  "6.NS.4": "Find GCF and LCM",
  "6.NS.5": "Understand positive and negative numbers",
  "6.NS.6": "Understand rational numbers as points on number line",
  "6.NS.7": "Understand ordering and absolute value of rationals",
  "6.NS.8": "Solve problems by graphing points in coordinate plane",
  "6.EE.1": "Write and evaluate numerical expressions with exponents",
  "6.EE.2": "Write, read, and evaluate algebraic expressions",
  "6.EE.3": "Apply properties of operations to generate equivalent expressions",
  "6.EE.4": "Identify equivalent expressions",
  "6.EE.5": "Understand solving equations or inequalities",
  "6.EE.6": "Use variables to represent numbers",
  "6.EE.7": "Solve real-world problems with equations",
  "6.EE.8": "Write inequalities and graph solutions",
  "6.EE.9": "Use variables to represent two related quantities",
  "6.G.1": "Find area of polygons by composing/decomposing",
  "6.G.2": "Find volume of right rectangular prisms with fractions",
  "6.G.3": "Draw polygons in coordinate plane given coordinates",
  "6.G.4": "Represent 3D figures using nets",
  "6.SP.1": "Recognize statistical questions",
  "6.SP.2": "Understand data distribution described by center, spread, shape",
  "6.SP.3": "Recognize measures of center as a single value",
  "6.SP.4": "Display numerical data in plots",
  "6.SP.5": "Summarize numerical data sets",
};
